In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import warnings
warnings.filterwarnings('ignore')

Reading in the data

In [2]:
x_train_gr_smpl = pd.read_csv("./new_4000_all_classes/x_train_4000_with_y_train_smpl.csv", delimiter=",")
x_test_data = pd.read_csv("./new_4000_all_classes/x_test_4000_with_y_test_smpl.csv", delimiter=",")

In [3]:
x_test = x_test_data.iloc[:, 0:1600]
y_test = x_test_data.iloc[:,-1].astype(int)

In [4]:
x = x_train_gr_smpl.iloc[:, 0:1600]
y = x_train_gr_smpl.iloc[:,-1].astype(int)
X_train, X_test_from_train,  y_train,  y_test_from_train = train_test_split(x, y, test_size=.33, random_state=17)

In [5]:
def printReports(nn):
    nn.fit(X_train,y_train)
    y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
    print("Results using train set")
    print(nn.score(X_train, y_train))
    print("\n")
    print("Confusion matrix from ten cross validation:") 
    print(confusion_matrix(y_test_from_train, y_train_pred))
    print("\n")
    print("Classification report")
    print(classification_report(y_test_from_train, y_train_pred))
    print("\nUsing test set ------------------------------------------------------------")
    print("Results using test set:") 
    print(nn.score(x_test,y_test))
    y_test_pred=nn.predict(x_test)
    print("\n")
    print("Confusion matrix using test set:") 
    print(confusion_matrix(y_test, y_test_pred))
    print("\nClassification report:")
    print(classification_report(y_test, y_test_pred))

## Changing the layers 

In [6]:
nn = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn)

Results using train set
0.8252025512842613


Confusion matrix from ten cross validation:
[[138 136   0  11   3   5   0   0  11   0]
 [ 52 328   2  23   5   7   0   0  15   0]
 [  0  11  85   1   8   0   0   0   4   0]
 [  1   6   0 279   9   1   0   0   5   0]
 [  6  18   2   8 418   7   0   0  32   1]
 [  1   1   0   0  14 432   1   0   5   1]
 [  1   3   0   0   8  12 139   0   6   0]
 [  3   7  23   2  11   0   0   1   5   0]
 [  2   7   0   0  16  13   1   0 440   0]
 [  0   6   0   0  12   7   4   0   4  32]]


Classification report
              precision    recall  f1-score   support

           0       0.68      0.45      0.54       304
           1       0.63      0.76      0.69       432
           2       0.76      0.78      0.77       109
           3       0.86      0.93      0.89       301
           4       0.83      0.85      0.84       492
           5       0.89      0.95      0.92       455
           6       0.96      0.82      0.89       169
           7       1.00

In [7]:
nn2 = MLPClassifier(hidden_layer_sizes=(10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn2)

Results using train set
0.9243233925185312


Confusion matrix from ten cross validation:
[[159 127   0   3   2   3   0   0  10   0]
 [ 48 357   0   5   4   4   1   0  13   0]
 [  1   5  71   0  23   0   4   0   5   0]
 [  8  17   0 252   9   7   0   0   7   1]
 [  4   9   6   6 448   3   5   0  11   0]
 [  6   0   0   3   5 429   6   0   4   2]
 [  1   1   1   0   8   1 141   0  16   0]
 [  3   5  20   0  15   1   0   2   6   0]
 [  1   3   0   1   8   3   5   0 458   0]
 [  1   9   0   5  14   6   3   0   1  26]]


Classification report
              precision    recall  f1-score   support

           0       0.69      0.52      0.59       304
           1       0.67      0.83      0.74       432
           2       0.72      0.65      0.69       109
           3       0.92      0.84      0.88       301
           4       0.84      0.91      0.87       492
           5       0.94      0.94      0.94       455
           6       0.85      0.83      0.84       169
           7       1.00

In [8]:
nn3 = MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

Results using train set
0.9294949146698845


Confusion matrix from ten cross validation:
[[200  92   0   0   2   4   1   0   5   0]
 [ 65 342   0   1  13   3   4   0   4   0]
 [  1   3  80   2  15   0   2   1   5   0]
 [  0   5   1 270  16   1   1   0   7   0]
 [  5  18   6   4 438   3   7   0  11   0]
 [ 15   4   0   0   2 415   6   0   9   4]
 [  5   5   1   0   4   4 141   0   9   0]
 [  2   4  19   4  15   0   1   2   5   0]
 [  9   5   1   3  11   3   3   0 442   2]
 [  2   6   0   1   4   8   7   0   1  36]]


Classification report
              precision    recall  f1-score   support

           0       0.66      0.66      0.66       304
           1       0.71      0.79      0.75       432
           2       0.74      0.73      0.74       109
           3       0.95      0.90      0.92       301
           4       0.84      0.89      0.87       492
           5       0.94      0.91      0.93       455
           6       0.82      0.83      0.82       169
           7       0.67

## Changing the neurons 

In [9]:
nn5 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn5)

Results using train set
0.9360455093949319


Confusion matrix from ten cross validation:
[[220  69   0   0   3   4   0   0   8   0]
 [ 45 372   0   3   2   3   0   0   7   0]
 [  0   3  99   0   4   0   0   3   0   0]
 [  0   4   0 284  11   0   0   0   2   0]
 [  3  14   0   6 458   3   0   0   8   0]
 [  1   2   0   0   7 438   1   0   5   1]
 [  1   1   0   0   2   0 162   0   3   0]
 [  6   2  22   0   8   0   0  11   3   0]
 [  2   6   0   0   7   1   0   0 463   0]
 [  0   2   0   1   2   0   0   0   0  60]]


Classification report
              precision    recall  f1-score   support

           0       0.79      0.72      0.76       304
           1       0.78      0.86      0.82       432
           2       0.82      0.91      0.86       109
           3       0.97      0.94      0.95       301
           4       0.91      0.93      0.92       492
           5       0.98      0.96      0.97       455
           6       0.99      0.96      0.98       169
           7       0.79

In [10]:
nn3 = MLPClassifier(hidden_layer_sizes=(30,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

Results using train set
0.9369074297534907


Confusion matrix from ten cross validation:
[[230  62   0   0   3   3   0   0   6   0]
 [ 38 381   0   1   2   3   0   0   7   0]
 [  0   2 102   0   3   0   0   2   0   0]
 [  0   2   0 286  11   0   0   0   2   0]
 [  4  12   0   6 461   2   0   0   7   0]
 [  1   1   0   0   6 441   1   0   5   0]
 [  0   2   0   0   1   0 163   0   3   0]
 [  8   0  14   0   7   1   0  19   3   0]
 [  6   2   0   0   8   0   0   0 463   0]
 [  0   0   0   0   3   0   0   0   0  62]]


Classification report
              precision    recall  f1-score   support

           0       0.80      0.76      0.78       304
           1       0.82      0.88      0.85       432
           2       0.88      0.94      0.91       109
           3       0.98      0.95      0.96       301
           4       0.91      0.94      0.92       492
           5       0.98      0.97      0.97       455
           6       0.99      0.96      0.98       169
           7       0.90

In [11]:
nn4 = MLPClassifier(hidden_layer_sizes=(50,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn4)

Results using train set
0.9588002068608861


Confusion matrix from ten cross validation:
[[238  55   0   0   3   2   0   0   6   0]
 [ 22 394   0   2   2   4   0   0   8   0]
 [  1   1 100   0   2   0   0   5   0   0]
 [  0   4   0 287   8   0   0   0   2   0]
 [  1  12   0   7 462   1   0   3   6   0]
 [  2   1   0   0   8 440   1   0   3   0]
 [  1   1   0   0   1   0 163   0   3   0]
 [  5   0   9   0   4   0   0  33   1   0]
 [  3   3   0   0   7   0   0   0 466   0]
 [  0   1   0   0   1   0   0   0   0  63]]


Classification report
              precision    recall  f1-score   support

           0       0.87      0.78      0.82       304
           1       0.83      0.91      0.87       432
           2       0.92      0.92      0.92       109
           3       0.97      0.95      0.96       301
           4       0.93      0.94      0.93       492
           5       0.98      0.97      0.98       455
           6       0.99      0.96      0.98       169
           7       0.80

## Changing iterations 

In [12]:
nn6 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=50)
printReports(nn6)

Results using train set
0.7155662816755731


Confusion matrix from ten cross validation:
[[ 76 178   0   1   8  11   4   0  26   0]
 [ 51 332   0   4  12   2   3   0  28   0]
 [  2   5  29   0  69   0   0   0   4   0]
 [  0   6   0 267  26   0   0   0   2   0]
 [  2  33   0   2 421   4   0   0  30   0]
 [  0   8   0   1  12 421   0   0  13   0]
 [  5   5   0   0   2   1 121   0  35   0]
 [  6   5  14   0  25   1   0   0   1   0]
 [  7  11   0   0   4   4   1   0 452   0]
 [  1  23   1   0  13  12   1   0  10   4]]


Classification report
              precision    recall  f1-score   support

           0       0.51      0.25      0.33       304
           1       0.55      0.77      0.64       432
           2       0.66      0.27      0.38       109
           3       0.97      0.89      0.93       301
           4       0.71      0.86      0.78       492
           5       0.92      0.93      0.92       455
           6       0.93      0.72      0.81       169
           7       0.00

In [13]:
nn7 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=100)
printReports(nn7)

Results using train set
0.8657128081365282


Confusion matrix from ten cross validation:
[[125 156   0   0   4   6   0   0  13   0]
 [ 60 341   0   1   9   2   0   0  19   0]
 [  1   5  81   0  19   0   0   0   3   0]
 [  0   3   0 281  16   0   0   0   1   0]
 [  3  20   0   6 446   5   0   0  12   0]
 [  1   2   0   0  11 436   0   0   5   0]
 [  4   5   0   0   3   1 148   0   8   0]
 [  5   6  25   0  13   1   0   0   2   0]
 [  5   8   1   0   4   0   1   0 460   0]
 [  1   7   0   0   7  12   1   0   3  34]]


Classification report
              precision    recall  f1-score   support

           0       0.61      0.41      0.49       304
           1       0.62      0.79      0.69       432
           2       0.76      0.74      0.75       109
           3       0.98      0.93      0.95       301
           4       0.84      0.91      0.87       492
           5       0.94      0.96      0.95       455
           6       0.99      0.88      0.93       169
           7       0.00

## Change learning rate

In [14]:
nn8 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.01,max_iter=200)

printReports(nn8)

Results using train set
0.9138079641441131


Confusion matrix from ten cross validation:
[[265  30   0   0   2   2   1   0   4   0]
 [ 17 402   1   1   7   2   0   0   2   0]
 [  0   1 101   0   2   0   0   5   0   0]
 [  3   3   1 283   8   0   0   0   3   0]
 [  3   8   0   4 469   4   0   2   2   0]
 [  1   2   1   1  10 434   0   1   5   0]
 [  1   1   0   0   2   1 164   0   0   0]
 [  2   1   5   0   2   0   0  42   0   0]
 [  2   0   0   0   8   1   2   1 465   0]
 [  0   1   0   0   0   0   0   0   0  64]]


Classification report
              precision    recall  f1-score   support

           0       0.90      0.87      0.89       304
           1       0.90      0.93      0.91       432
           2       0.93      0.93      0.93       109
           3       0.98      0.94      0.96       301
           4       0.92      0.95      0.94       492
           5       0.98      0.95      0.97       455
           6       0.98      0.97      0.98       169
           7       0.82

In [15]:
nn9 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.1,max_iter=200)
printReports(nn9)

Results using train set
0.17428029650060334


Confusion matrix from ten cross validation:
[[137  99   2   1  44   3   0   1  17   0]
 [ 55 297   5   7  55   2   0   0  11   0]
 [  3  17  60   2  26   0   0   0   1   0]
 [  3  20   0 191  81   0   2   1   2   1]
 [  8  19   2   2 435   1   3   1  21   0]
 [  5  10   0   1  52 362   0   0  25   0]
 [  0   1   0   2  24  33  91   0  18   0]
 [  5   8   9   0  19   0   0   9   2   0]
 [  2   8   0   2  87  35   5   1 339   0]
 [  3   2   0   0  15  10   2   0   9  24]]


Classification report
              precision    recall  f1-score   support

           0       0.62      0.45      0.52       304
           1       0.62      0.69      0.65       432
           2       0.77      0.55      0.64       109
           3       0.92      0.63      0.75       301
           4       0.52      0.88      0.65       492
           5       0.81      0.80      0.80       455
           6       0.88      0.54      0.67       169
           7       0.6

## Change momentum

In [16]:
nn10 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.7,learning_rate_init=0.001,max_iter=200)
printReports(nn10)

Results using train set
0.9413894156179969


Confusion matrix from ten cross validation:
[[214  75   0   0   3   5   0   0   7   0]
 [ 42 370   0   2   2   5   0   0  11   0]
 [  1   3  98   0   6   0   0   0   1   0]
 [  0   6   0 281  12   0   0   0   2   0]
 [  4  16   1   5 458   3   0   0   5   0]
 [  2   2   0   0   7 437   1   0   6   0]
 [  1   1   0   0   2   0 157   0   8   0]
 [  7   2  29   0   7   1   0   4   2   0]
 [  7   2   0   0   8   2   0   0 460   0]
 [  0   0   0   1   4   1   0   0   0  59]]


Classification report
              precision    recall  f1-score   support

           0       0.77      0.70      0.74       304
           1       0.78      0.86      0.81       432
           2       0.77      0.90      0.83       109
           3       0.97      0.93      0.95       301
           4       0.90      0.93      0.92       492
           5       0.96      0.96      0.96       455
           6       0.99      0.93      0.96       169
           7       1.00

In [17]:
nn11 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.5,learning_rate_init=0.001,max_iter=200)

printReports(nn11)

Results using train set
0.9300120668850198


Confusion matrix from ten cross validation:
[[213  76   0   0   3   5   1   0   6   0]
 [ 43 370   0   2   2   5   0   0  10   0]
 [  1   3  95   0   7   0   0   3   0   0]
 [  0   5   0 281  13   0   0   0   2   0]
 [  1  13   0   6 464   2   0   0   6   0]
 [  1   0   0   0   9 438   1   0   6   0]
 [  0   3   0   0   2   0 159   0   5   0]
 [  7   2  24   0   6   1   0  11   1   0]
 [  2   3   0   0   5   1   2   0 466   0]
 [  0   0   0   0   3   0   0   0   0  62]]


Classification report
              precision    recall  f1-score   support

           0       0.79      0.70      0.74       304
           1       0.78      0.86      0.82       432
           2       0.80      0.87      0.83       109
           3       0.97      0.93      0.95       301
           4       0.90      0.94      0.92       492
           5       0.97      0.96      0.97       455
           6       0.98      0.94      0.96       169
           7       0.79

## Change Validation Fraction

In [18]:
nn13 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.5)
printReports(nn13)

Results using train set
0.9279434580244785


Confusion matrix from ten cross validation:
[[128 138   1   1   6  15   2   0  13   0]
 [ 57 329   0   3  10  13   0   0  19   1]
 [  1   5  60   0  41   0   0   1   1   0]
 [  1  21   0 253  20   2   0   0   4   0]
 [  9  27   0   6 429   6   0   0  15   0]
 [  1  10   0   2  20 415   0   0   7   0]
 [  3   7   0   0  12   0 130   0  17   0]
 [  5   9  18   0  17   2   0   1   0   0]
 [  4  17   0   0  16   1   1   0 440   0]
 [  0  12   0   0   6  17   3   0   3  24]]


Classification report
              precision    recall  f1-score   support

           0       0.61      0.42      0.50       304
           1       0.57      0.76      0.65       432
           2       0.76      0.55      0.64       109
           3       0.95      0.84      0.89       301
           4       0.74      0.87      0.80       492
           5       0.88      0.91      0.90       455
           6       0.96      0.77      0.85       169
           7       0.50

In [19]:
nn12 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.7)
printReports(nn12)

Results using train set
0.8860541285985175


Confusion matrix from ten cross validation:
[[ 52 180   1   1  18  10   6   0  36   0]
 [ 41 310   0   3  25   4   0   0  49   0]
 [  0   7  26   0  68   0   0   0   8   0]
 [  0  10   0 239  29   0   0   0  23   0]
 [  2  30   0   6 399   2   0   0  53   0]
 [  0   7   0   0  12 382   0   0  54   0]
 [  4   3   1   0   9   1 104   0  47   0]
 [  3  10   6   0  30   1   0   0   2   0]
 [  5  12   2   0  24   3   2   0 431   0]
 [  0  13   0   1  12  17   0   0  10  12]]


Classification report
              precision    recall  f1-score   support

           0       0.49      0.17      0.25       304
           1       0.53      0.72      0.61       432
           2       0.72      0.24      0.36       109
           3       0.96      0.79      0.87       301
           4       0.64      0.81      0.71       492
           5       0.91      0.84      0.87       455
           6       0.93      0.62      0.74       169
           7       0.00