In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import warnings
warnings.filterwarnings('ignore')

Reading in the data

In [6]:
x_train_gr_smpl = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")
x_test_data = pd.read_csv("x_test_normalised_with_y_test_smpl.csv", delimiter=",")

In [7]:
x_test = x_test_data.iloc[:, 0:1600]
y_test = x_test_data.iloc[:,-1].astype(int)

In [9]:
x = x_train_gr_smpl.iloc[:, 0:1600]
y = x_train_gr_smpl.iloc[:,-1].astype(int)
X_train, X_test_from_train,  y_train,  y_test_from_train = train_test_split(x, y, test_size=.33, random_state=17)

In [31]:
def printReports(nn):
    nn.fit(X_train,y_train)
    y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
    print("Results using train set")
    print(nn.score(X_train, y_train))
    print("\n")
    print("Confusion matrix from ten cross validation:") 
    print(confusion_matrix(y_test_from_train, y_train_pred))
    print("\n")
    print("Classification report")
    print(classification_report(y_test_from_train, y_train_pred))
    print("\nUsing test set ------------------------------------------------------------")
    print("Results using test set:") 
    print(nn.score(x_test,y_test))
    y_test_pred=nn.predict(x_test)
    print("\n")
    print("Confusion matrix using test set:") 
    print(confusion_matrix(y_test, y_test_pred))
    print("\nClassification report:")
    print(classification_report(y_test, y_test_pred))

## Changing the layers 

In [16]:
nn = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn)

Results using train set
0.952959207734025


Confusion matrix from ten cross validation:
[[219 200   0   1   5  12   2   0   8   0]
 [ 59 509   1   4  11   7   0   0  12   1]
 [  2   3 112   1  18   0   0   4   0   0]
 [  7  10   2 415  16   0   0   0   4   0]
 [  7   8   2   2 650   5   4   1  10   0]
 [  5   2   0   1  19 699   6   0   7   2]
 [  0   0   0   0   8   1 217   0  13   0]
 [  3   9  33   2  21   0   0   8   8   0]
 [  6   5   0   0   5   4   2   0 682   0]
 [  5   8   0   0  10  17   2   0   0  34]]


Classification report
              precision    recall  f1-score   support

           0       0.70      0.49      0.58       447
           1       0.68      0.84      0.75       604
           2       0.75      0.80      0.77       140
           3       0.97      0.91      0.94       454
           4       0.85      0.94      0.90       689
           5       0.94      0.94      0.94       741
           6       0.93      0.91      0.92       239
           7       0.62 

In [17]:
nn2 = MLPClassifier(hidden_layer_sizes=(10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn2)

Results using train set
0.9041499646309833


Confusion matrix from ten cross validation:
[[319 113   1   1   2   9   1   0   1   0]
 [ 64 515   2   2  11   5   0   0   4   1]
 [  1   2 124   0   4   0   0   9   0   0]
 [  2   8   1 423  16   0   0   0   3   1]
 [  4  18   3   9 641   3   1   2   8   0]
 [ 11   6   0   1  10 699   3   1   8   2]
 [  2   1   0   0   0   1 225   0   8   2]
 [  6   4  15   2  10   0   0  47   0   0]
 [ 11   3   0   2   8   4   3   1 672   0]
 [  0   5   0   6   0   2   0   0   0  63]]


Classification report
              precision    recall  f1-score   support

           0       0.76      0.71      0.74       447
           1       0.76      0.85      0.81       604
           2       0.85      0.89      0.87       140
           3       0.95      0.93      0.94       454
           4       0.91      0.93      0.92       689
           5       0.97      0.94      0.95       741
           6       0.97      0.94      0.95       239
           7       0.78

In [18]:
nn3 = MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

Results using train set
0.9476538552228249


Confusion matrix from ten cross validation:
[[333  96   0   2   4   4   1   0   6   1]
 [ 53 520   3   5  10   8   1   0   3   1]
 [  0   5 100   3  25   0   0   6   1   0]
 [  2   8   2 415  17   4   3   0   3   0]
 [ 15  11   9   6 630   3   4   2   8   1]
 [ 16   6   0   2   9 691   2   1  13   1]
 [  5   2   1   2   5   1 213   0   8   2]
 [  4   4  18   0  19   0   3  30   6   0]
 [ 14   0   2   2  14   8   7   1 654   2]
 [  5   9   0   7   4   1   2   0   5  43]]


Classification report
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       447
           1       0.79      0.86      0.82       604
           2       0.74      0.71      0.73       140
           3       0.93      0.91      0.92       454
           4       0.85      0.91      0.88       689
           5       0.96      0.93      0.95       741
           6       0.90      0.89      0.90       239
           7       0.75

## Changing the neurons 

In [19]:
nn5 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn5)

Results using train set
0.9674605045979722


Confusion matrix from ten cross validation:
[[341  91   1   0   3   6   0   0   5   0]
 [ 44 529   0   3  11   6   1   0   9   1]
 [  2   0 128   0   3   0   0   7   0   0]
 [  1   4   0 433  13   0   0   0   3   0]
 [  4  15   0  10 651   4   1   1   3   0]
 [  2   2   1   4  14 709   2   0   6   1]
 [  1   0   0   0   1   0 234   0   3   0]
 [  9   2   9   0   7   1   0  55   1   0]
 [  5   5   0   0   7   5   0   0 682   0]
 [  1   2   0   1   3   2   0   0   0  67]]


Classification report
              precision    recall  f1-score   support

           0       0.83      0.76      0.80       447
           1       0.81      0.88      0.84       604
           2       0.92      0.91      0.92       140
           3       0.96      0.95      0.96       454
           4       0.91      0.94      0.93       689
           5       0.97      0.96      0.96       741
           6       0.98      0.98      0.98       239
           7       0.87

In [21]:
nn3 = MLPClassifier(hidden_layer_sizes=(30,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

Results using train set
0.9735911341664701


Confusion matrix from ten cross validation:
[[378  61   0   1   1   4   0   0   2   0]
 [ 29 552   0   1   9   9   0   0   4   0]
 [  2   0 131   0   3   0   0   4   0   0]
 [  0   6   0 436   9   0   0   1   2   0]
 [  2  17   1  10 645   7   0   0   7   0]
 [  0   3   1   1  15 713   0   0   7   1]
 [  0   0   0   0   1   1 233   0   4   0]
 [  9   2   4   0   3   1   0  63   2   0]
 [  4   6   0   0   7   4   1   0 682   0]
 [  0   2   0   0   1   1   0   0   0  72]]


Classification report
              precision    recall  f1-score   support

           0       0.89      0.85      0.87       447
           1       0.85      0.91      0.88       604
           2       0.96      0.94      0.95       140
           3       0.97      0.96      0.97       454
           4       0.93      0.94      0.93       689
           5       0.96      0.96      0.96       741
           6       1.00      0.97      0.99       239
           7       0.93

In [22]:
nn4 = MLPClassifier(hidden_layer_sizes=(50,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn4)

Results using train set
0.9836123555765149


Confusion matrix from ten cross validation:
[[387  49   1   0   3   5   0   0   2   0]
 [ 31 552   0   1   7   6   0   0   6   1]
 [  1   0 133   0   2   0   0   4   0   0]
 [  0   5   0 435  10   0   0   2   2   0]
 [  2  14   0   7 655   4   0   2   5   0]
 [  2   2   1   2  14 715   0   0   5   0]
 [  0   0   0   0   1   0 236   0   2   0]
 [  9   0   2   0   2   0   0  70   1   0]
 [  6   3   0   1   4   3   0   0 687   0]
 [  0   1   0   0   1   1   0   0   0  73]]


Classification report
              precision    recall  f1-score   support

           0       0.88      0.87      0.87       447
           1       0.88      0.91      0.90       604
           2       0.97      0.95      0.96       140
           3       0.98      0.96      0.97       454
           4       0.94      0.95      0.94       689
           5       0.97      0.96      0.97       741
           6       1.00      0.99      0.99       239
           7       0.90

## Changing iterations 

In [23]:
nn6 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=50)
printReports(nn6)

Results using train set
0.8904739448243338


Confusion matrix from ten cross validation:
[[174 211   0   3  10  19   8   0  22   0]
 [ 84 466   0   5  19  11   1   0  18   0]
 [  2  13  77   0  44   0   0   0   4   0]
 [  0   7   0 400  38   1   0   0   8   0]
 [  4  36   0  12 600   5   2   0  30   0]
 [  2   4   0   1  23 693   0   0  18   0]
 [ 11   4   0   1   2   0 176   0  45   0]
 [  6   3  25   0  44   1   2   1   2   0]
 [ 15   5   0   1   8   5   5   0 665   0]
 [  4  14   0   1  19  27   0   0   7   4]]


Classification report
              precision    recall  f1-score   support

           0       0.58      0.39      0.46       447
           1       0.61      0.77      0.68       604
           2       0.75      0.55      0.64       140
           3       0.94      0.88      0.91       454
           4       0.74      0.87      0.80       689
           5       0.91      0.94      0.92       741
           6       0.91      0.74      0.81       239
           7       1.00

In [24]:
nn7 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=100)
printReports(nn7)

Results using train set
0.9464748879981136


Confusion matrix from ten cross validation:
[[259 147   0   1   8   9   4   0  19   0]
 [ 73 495   1   6  10   6   0   0  13   0]
 [  0  11 109   0  20   0   0   0   0   0]
 [  2   4   0 423  21   0   0   0   4   0]
 [  9  23   0   7 634   7   0   0   9   0]
 [  3   1   0   2  18 707   0   0  10   0]
 [  2   0   0   1   5   0 206   0  25   0]
 [  7   2  34   1  21   1   0  14   4   0]
 [  9  10   0   0   5   4   3   0 673   0]
 [  2   7   0   1   8  12   3   0  10  33]]


Classification report
              precision    recall  f1-score   support

           0       0.71      0.58      0.64       447
           1       0.71      0.82      0.76       604
           2       0.76      0.78      0.77       140
           3       0.96      0.93      0.94       454
           4       0.85      0.92      0.88       689
           5       0.95      0.95      0.95       741
           6       0.95      0.86      0.91       239
           7       1.00

## Change learning rate

In [25]:
nn8 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.01,max_iter=200)

printReports(nn8)

Results using train set
0.9911577458146663


Confusion matrix from ten cross validation:
[[410  26   1   1   2   2   2   0   3   0]
 [ 24 562   0   0   9   6   0   0   3   0]
 [  1   1 131   0   1   0   0   6   0   0]
 [  3   5   0 434   6   0   2   1   2   1]
 [  1  11   2   8 651   7   0   1   8   0]
 [  4   1   1   3   7 717   0   1   7   0]
 [  0   0   0   0   0   1 235   0   3   0]
 [  2   0   2   0   2   0   0  77   1   0]
 [  2   1   0   1   6   1   4   1 688   0]
 [  0   0   0   0   0   2   0   0   0  74]]


Classification report
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       447
           1       0.93      0.93      0.93       604
           2       0.96      0.94      0.95       140
           3       0.97      0.96      0.96       454
           4       0.95      0.94      0.95       689
           5       0.97      0.97      0.97       741
           6       0.97      0.98      0.98       239
           7       0.89

In [26]:
nn9 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.1,max_iter=200)
printReports(nn9)

Results using train set
0.5506955906625796


Confusion matrix from ten cross validation:
[[211  94   0   1  48  59   1   0  32   1]
 [ 60 358   5   2  81  63   2   0  31   2]
 [  0   6  68  24  25  14   1   2   0   0]
 [  3   4   2 327  59  49   2   1   7   0]
 [  6  33   3  82 465  71  10   5  12   2]
 [ 15  11   0   1  80 599   2   0  29   4]
 [  4  10   0   0  33  27 119   0  46   0]
 [  3  10   6  17  22   9   0  16   1   0]
 [  9   3   0   6 101  90   5   1 489   0]
 [  2   8   0   1   9  17   3   0  13  23]]


Classification report
              precision    recall  f1-score   support

           0       0.67      0.47      0.56       447
           1       0.67      0.59      0.63       604
           2       0.81      0.49      0.61       140
           3       0.71      0.72      0.71       454
           4       0.50      0.67      0.58       689
           5       0.60      0.81      0.69       741
           6       0.82      0.50      0.62       239
           7       0.64

## Change momentum

In [27]:
nn10 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.7,learning_rate_init=0.001,max_iter=200)
printReports(nn10)

Results using train set
0.9704079226597501


Confusion matrix from ten cross validation:
[[358  77   0   0   3   4   0   0   5   0]
 [ 54 523   0   2   9   9   0   0   6   1]
 [  2   0 130   0   3   0   0   5   0   0]
 [  0   9   0 431  12   0   0   1   1   0]
 [  6  17   1   8 647   5   0   0   5   0]
 [  1   2   1   3  15 711   0   0   7   1]
 [  1   0   0   0   1   0 233   0   4   0]
 [ 13   0   6   0   3   1   0  60   1   0]
 [  5   5   0   0   9   4   1   0 680   0]
 [  1   1   0   0   3   1   0   0   0  70]]


Classification report
              precision    recall  f1-score   support

           0       0.81      0.80      0.81       447
           1       0.82      0.87      0.84       604
           2       0.94      0.93      0.94       140
           3       0.97      0.95      0.96       454
           4       0.92      0.94      0.93       689
           5       0.97      0.96      0.96       741
           6       1.00      0.97      0.99       239
           7       0.91

In [28]:
nn11 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.5,learning_rate_init=0.001,max_iter=200)

printReports(nn11)

Results using train set
0.9711153029945767


Confusion matrix from ten cross validation:
[[354  76   1   0   2   9   0   0   5   0]
 [ 40 536   2   1   8   8   2   0   7   0]
 [  2   0 129   0   4   0   0   5   0   0]
 [  0   7   0 431  12   1   0   1   2   0]
 [  7  16   0   9 646   4   0   0   7   0]
 [  2   0   0   2  15 714   1   0   6   1]
 [  1   0   0   0   1   1 234   0   2   0]
 [  8   2  14   0   2   0   0  55   3   0]
 [  7   5   0   0   4   5   0   0 683   0]
 [  2   2   0   0   4   2   4   0   0  62]]


Classification report
              precision    recall  f1-score   support

           0       0.84      0.79      0.81       447
           1       0.83      0.89      0.86       604
           2       0.88      0.92      0.90       140
           3       0.97      0.95      0.96       454
           4       0.93      0.94      0.93       689
           5       0.96      0.96      0.96       741
           6       0.97      0.98      0.98       239
           7       0.90

## Change Validation Fraction

In [32]:
nn13 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.5)
printReports(nn13)

Results using train set
0.9356283895307711


Confusion matrix from ten cross validation:
[[277 138   0   0   5  12   1   0  14   0]
 [ 82 487   1   7   7   6   1   0  11   2]
 [  1   7 123   0   8   0   0   1   0   0]
 [  0   6   0 426  19   0   0   0   3   0]
 [  7  24   0  12 625   5   1   0  15   0]
 [  2   3   0   2  18 702   1   0  12   1]
 [  1   0   0   0   2   3 227   0   6   0]
 [  6   4  31   1  14   1   0  24   3   0]
 [ 10   4   0   0   9   8   0   0 673   0]
 [  2   6   0   3   7   8   0   0   0  50]]


Classification report
              precision    recall  f1-score   support

           0       0.71      0.62      0.66       447
           1       0.72      0.81      0.76       604
           2       0.79      0.88      0.83       140
           3       0.94      0.94      0.94       454
           4       0.88      0.91      0.89       689
           5       0.94      0.95      0.94       741
           6       0.98      0.95      0.97       239
           7       0.96

In [33]:
nn12 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.7)
printReports(nn12)

Results using train set
0.9306767271869842


Confusion matrix from ten cross validation:
[[184 206   0   1  11  15   5   0  25   0]
 [ 86 465   0   5  11   9   1   0  26   1]
 [  1  13 100   0  23   0   0   2   1   0]
 [  1   6   0 410  31   1   0   0   5   0]
 [  5  42   1   3 607   5   1   0  25   0]
 [  3   4   0   0  25 692   2   0  15   0]
 [  6   1   0   0   2   2 199   0  29   0]
 [  8   2  29   0  28   0   0  13   4   0]
 [ 12   7   0   3  11   5   4   0 662   0]
 [  5  11   0   2  11  24   1   0   2  20]]


Classification report
              precision    recall  f1-score   support

           0       0.59      0.41      0.49       447
           1       0.61      0.77      0.68       604
           2       0.77      0.71      0.74       140
           3       0.97      0.90      0.93       454
           4       0.80      0.88      0.84       689
           5       0.92      0.93      0.93       741
           6       0.93      0.83      0.88       239
           7       0.87