In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import pandas_ml as pdml
import warnings
warnings.filterwarnings('ignore')

Reading in the data

In [2]:
x_train_gr_smpl = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")
x_test_data = pd.read_csv("x_test_normalised_with_y_test_smpl.csv", delimiter=",")

In [3]:
x_test = x_test_data.iloc[:, 0:1600]
y_test = x_test_data.iloc[:,-1].astype(int)

In [4]:
x = x_train_gr_smpl.iloc[:, 0:1600]
y = x_train_gr_smpl.iloc[:,-1].astype(int)
X_train, X_test_from_train,  y_train,  y_test_from_train = train_test_split(x, y, test_size=.33, random_state=17)

In [5]:
def printReports(nn):
    nn.fit(X_train,y_train)
    y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
    print("Results using train set")
    print(nn.score(X_train, y_train))
    print("\n")
    print("Confusion matrix from ten cross validation:") 
    print(confusion_matrix(y_test_from_train, y_train_pred))
    print("\n")
    print("Classification report")
    print(classification_report(y_test_from_train, y_train_pred))
    print("\nUsing test set ------------------------------------------------------------")
    print("Results using test set:") 
    print(nn.score(x_test,y_test))
    y_test_pred=nn.predict(x_test)
    print("\n")
    print("Confusion matrix using test set:") 
    print(confusion_matrix(y_test, y_test_pred))
    print("\nClassification report:")
    print(classification_report(y_test, y_test_pred))
    print("Metrics =======================================================================")
    cm = pdml.ConfusionMatrix(y_test, y_train_pred)
    stats = cm.stats()
    print(stats)

In [6]:
nn = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)

In [7]:
nn.fit(X_train,y_train)
y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
print("Results using train set")
print(nn.score(X_train, y_train))
print("\n")
print("Confusion matrix from ten cross validation:") 
print(confusion_matrix(y_test_from_train, y_train_pred))
print("\n")
print("Classification report")
print(classification_report(y_test_from_train, y_train_pred))
print("\nUsing test set ------------------------------------------------------------")
print("Results using test set:") 
print(nn.score(x_test,y_test))
y_test_pred=nn.predict(x_test)
print("\n")
print("Confusion matrix using test set:") 
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification report:")
print(classification_report(y_test, y_test_pred))
print("Metrics =======================================================================")

Results using train set
0.9777175194529593


Confusion matrix from ten cross validation:
[[345  85   0   0   1   7   1   0   8   0]
 [ 58 517   0   3  12   6   2   0   6   0]
 [  2   0 127   0   3   0   0   7   1   0]
 [  0   5   0 429  16   0   1   1   2   0]
 [  5  18   0   7 646   6   0   1   6   0]
 [  1   4   1   5  14 710   0   0   6   0]
 [  0   0   0   0   2   2 228   0   7   0]
 [  9   1  20   0   8   1   0  43   2   0]
 [  5   4   0   0   8   5   0   0 682   0]
 [  0   3   0   1   2   6   0   0   0  64]]


Classification report
              precision    recall  f1-score   support

           0       0.81      0.77      0.79       447
           1       0.81      0.86      0.83       604
           2       0.86      0.91      0.88       140
           3       0.96      0.94      0.95       454
           4       0.91      0.94      0.92       689
           5       0.96      0.96      0.96       741
           6       0.98      0.95      0.97       239
           7       0.83

In [17]:
cm = pdml.ConfusionMatrix(y_test, y_test_pred)
stats = cm.stats()

In [9]:
stats['class']

Classes                                        0          1            2  \
Population                                  4170       4170         4170   
P: Condition positive                        450        630          150   
N: Condition negative                       3720       3540         4020   
Test outcome positive                        446        667          114   
Test outcome negative                       3724       3503         4056   
TP: True Positive                            393        592          110   
TN: True Negative                           3667       3465         4016   
FP: False Positive                            53         75            4   
FN: False Negative                            57         38           40   
TPR: (Sensitivity, hit rate, recall)    0.873333   0.939683     0.733333   
TNR=SPC: (Specificity)                  0.985753   0.978814     0.999005   
PPV: Pos Pred Value (Precision)         0.881166   0.887556     0.964912   
NPV: Neg Pred Value                     0.984694   0.989152     0.990138   
FPR: False-out                         0.0142473  0.0211864  0.000995025   
FDR: False Discovery Rate               0.118834   0.112444    0.0350877   
FNR: Miss Rate                          0.126667  0.0603175     0.266667   
ACC: Accuracy                           0.973621   0.972902     0.989448   
F1 score                                0.877232   0.912876     0.833333   
MCC: Matthews correlation coefficient   0.862466   0.897359     0.836313   
Informedness                            0.859086   0.918496     0.732338   
Markedness                               0.86586   0.876708      0.95505   
Prevalence                              0.107914   0.151079    0.0359712   
LR+: Positive likelihood ratio           61.2981     44.353          737   
LR-: Negative likelihood ratio          0.128497   0.061623     0.266932   
DOR: Diagnostic odds ratio               477.038    719.747         2761   
FOR: False omission rate               0.0153061  0.0108478   0.00986193   

Classes                                         3           4           5  \
Population                                   4170        4170        4170   
P: Condition positive                         420         690         720   
N: Condition negative                        3750        3480        3450   
Test outcome positive                         399         746         742   
Test outcome negative                        3771        3424        3428   
TP: True Positive                             396         663         711   
TN: True Negative                            3747        3397        3419   
FP: False Positive                              3          83          31   
FN: False Negative                             24          27           9   
TPR: (Sensitivity, hit rate, recall)     0.942857     0.96087      0.9875   
TNR=SPC: (Specificity)                     0.9992    0.976149    0.991014   
PPV: Pos Pred Value (Precision)          0.992481     0.88874    0.958221   
NPV: Neg Pred Value                      0.993636    0.992114    0.997375   
FPR: False-out                             0.0008   0.0238506  0.00898551   
FDR: False Discovery Rate               0.0075188     0.11126    0.041779   
FNR: Miss Rate                          0.0571429   0.0391304      0.0125   
ACC: Accuracy                            0.993525    0.973621    0.990408   
F1 score                                 0.967033    0.923398     0.97264   
MCC: Matthews correlation coefficient    0.963835    0.908503    0.966987   
Informedness                             0.942057    0.937019    0.978514   
Markedness                               0.986117    0.880854    0.955596   
Prevalence                               0.100719    0.165468    0.172662   
LR+: Positive likelihood ratio            1178.57     40.2871     109.899   
LR-: Negative likelihood ratio          0.0571886   0.0400865   0.0126133   
DOR: Diagnostic odds r

In [10]:
stats['class'].loc['TP: True Positive'].mean()

385.9

In [11]:
stats['class'].loc['FP: False Positive'].mean()

31.1

In [12]:
#Recall
stats['class'].loc['TPR: (Sensitivity, hit rate, recall)'].mean()

0.8726947895100068

In [13]:
stats['class'].loc['F1 score'].mean()

0.8892869350640954

In [14]:
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing

In [18]:
lb = preprocessing.LabelBinarizer()
lb.fit(y_test)
y_test_b = lb.transform(y_test)
y_test_pred_b = lb.transform(y_test_pred)
roc_auc_score(y_test_b, y_test_pred_b, average=None).mean()

0.9320158997936501