In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import pandas_ml as pdml
import warnings
warnings.filterwarnings('ignore')

Reading in the data

In [2]:
x_train_gr_smpl = pd.read_csv("./new_9000_all_classes/x_train_9000_with_y_train_smpl.csv", delimiter=",")
x_test_data = pd.read_csv("./new_9000_all_classes/x_test_9000_with_y_test_smpl.csv", delimiter=",")

In [3]:
x_test = x_test_data.iloc[:, 0:1600]
y_test = x_test_data.iloc[:,-1].astype(int)

In [4]:
x = x_train_gr_smpl.iloc[:, 0:1600]
y = x_train_gr_smpl.iloc[:,-1].astype(int)
X_train, X_test_from_train,  y_train,  y_test_from_train = train_test_split(x, y, test_size=.33, random_state=17)

In [5]:
def printReports(nn):
    nn.fit(X_train,y_train)
    y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
    print("Results using train set")
    print(nn.score(X_train, y_train))
    print("\n")
    print("Confusion matrix from ten cross validation:") 
    print(confusion_matrix(y_test_from_train, y_train_pred))
    print("\n")
    print("Classification report")
    print(classification_report(y_test_from_train, y_train_pred))
    print("\nUsing test set ------------------------------------------------------------")
    print("Results using test set:") 
    print(nn.score(x_test,y_test))
    y_test_pred=nn.predict(x_test)
    print("\n")
    print("Confusion matrix using test set:") 
    print(confusion_matrix(y_test, y_test_pred))
    print("\nClassification report:")
    print(classification_report(y_test, y_test_pred))
    print("Metrics =======================================================================")
    cm = pdml.ConfusionMatrix(y_test, y_train_pred)
    stats = cm.stats()
    print(stats)

In [6]:
nn = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)

In [7]:
nn.fit(X_train,y_train)
y_train_pred=cross_val_predict(nn,X_test_from_train,y_test_from_train,cv=10)
print("Results using train set")
print(nn.score(X_train, y_train))
print("\n")
print("Confusion matrix from ten cross validation:") 
print(confusion_matrix(y_test_from_train, y_train_pred))
print("\n")
print("Classification report")
print(classification_report(y_test_from_train, y_train_pred))
print("\nUsing test set ------------------------------------------------------------")
print("Results using test set:") 
print(nn.score(x_test,y_test))
y_test_pred=nn.predict(x_test)
print("\n")
print("Confusion matrix using test set:") 
print(confusion_matrix(y_test, y_test_pred))
print("\nClassification report:")
print(classification_report(y_test, y_test_pred))
print("Metrics =======================================================================")

Results using train set
0.9294165646674827


Confusion matrix from ten cross validation:
[[ 33  75   0   0   2   1   0   0   9   0]
 [ 22 161   0   3   4   1   0   0   4   1]
 [  0   5  31   0   5   0   0   0   0   0]
 [  0   1   0 117  13   0   0   0   3   0]
 [  1   5   0   5 166   3   0   0   7   0]
 [  1   2   0   3   1 196   1   0   6   0]
 [  0   1   0   0   0   1  46   0   8   0]
 [  1   4  14   1   8   0   0   1   1   0]
 [  2   3   0   0   1   1   0   0 198   0]
 [  0   5   0   1   3   5   0   0   1  14]]


Classification report
              precision    recall  f1-score   support

           0       0.55      0.28      0.37       120
           1       0.61      0.82      0.70       196
           2       0.69      0.76      0.72        41
           3       0.90      0.87      0.89       134
           4       0.82      0.89      0.85       187
           5       0.94      0.93      0.94       210
           6       0.98      0.82      0.89        56
           7       1.00

In [16]:
cm = pdml.ConfusionMatrix(y_test, y_test_pred)
stats = cm.stats()
stats

OrderedDict([('cm',
              Predicted     0     1    2     3     4     5    6    7     8    9  __all__
              Actual                                                                    
              0           967   434    3     3     8    23    1    0    23    0     1462
              1           116  1739    2     4    23    19    1    1    21    2     1928
              2             2    46  368     0    17     0    0   13     2    0      448
              3             0    11    0  1266    55     4    0    0     0    1     1337
              4             2    50    2    46  2034    21    0    1    26    0     2182
              5             7     9    0     6    11  2217    6    0    16    3     2275
              6            15     7    0     2    11     2  778    0    14    0      829
              7            20     7   32     0    48     3    1  113     4    0      228
              8            14    19    0     1    35    38   10    3  2055    0     2175
 

In [9]:
stats['class']

Classes                                        0          1           2  \
Population                                 13170      13170       13170   
P: Condition positive                       1462       1928         448   
N: Condition negative                      11708      11242       12722   
Test outcome positive                       1145       2334         407   
Test outcome negative                      12025      10836       12763   
TP: True Positive                            967       1739         368   
TN: True Negative                          11530      10647       12683   
FP: False Positive                           178        595          39   
FN: False Negative                           495        189          80   
TPR: (Sensitivity, hit rate, recall)    0.661423   0.901971    0.821429   
TNR=SPC: (Specificity)                  0.984797   0.947073    0.996934   
PPV: Pos Pred Value (Precision)         0.844541   0.745073    0.904177   
NPV: Neg Pred Value                     0.958836   0.982558    0.993732   
FPR: False-out                         0.0152033  0.0529265  0.00306556   
FDR: False Discovery Rate               0.155459   0.254927   0.0958231   
FNR: Miss Rate                          0.338577   0.098029    0.178571   
ACC: Accuracy                           0.948899   0.940471    0.990964   
F1 score                                0.741849   0.816049    0.860819   
MCC: Matthews correlation coefficient   0.720526   0.785997    0.857214   
Informedness                            0.646219   0.849044    0.818363   
Markedness                              0.803377   0.727631    0.897909   
Prevalence                               0.11101   0.146393   0.0340167   
LR+: Positive likelihood ratio           43.5053    17.0419     267.954   
LR-: Negative likelihood ratio          0.343804   0.103507    0.179121   
DOR: Diagnostic odds ratio               126.541    164.645     1495.94   
FOR: False omission rate               0.0411642  0.0174419  0.00626812   

Classes                                         3          4           5  \
Population                                  13170      13170       13170   
P: Condition positive                        1337       2182        2275   
N: Condition negative                       11833      10988       10895   
Test outcome positive                        1332       2251        2329   
Test outcome negative                       11838      10919       10841   
TP: True Positive                            1266       2034        2217   
TN: True Negative                           11767      10771       10783   
FP: False Positive                             66        217         112   
FN: False Negative                             71        148          58   
TPR: (Sensitivity, hit rate, recall)     0.946896   0.932172    0.974505   
TNR=SPC: (Specificity)                   0.994422   0.980251     0.98972   
PPV: Pos Pred Value (Precision)           0.95045   0.903598    0.951911   
NPV: Neg Pred Value                      0.994002   0.986446     0.99465   
FPR: False-out                         0.00557762  0.0197488   0.0102799   
FDR: False Discovery Rate               0.0495495  0.0964016   0.0480893   
FNR: Miss Rate                           0.053104  0.0678277   0.0254945   
ACC: Accuracy                            0.989598   0.972285    0.987092   
F1 score                                  0.94867   0.917663    0.963076   
MCC: Matthews correlation coefficient    0.942884   0.901164    0.955352   
Informedness                             0.941318   0.912424    0.964226   
Markedness                               0.944453   0.890044    0.946561   
Prevalence                               0.101519    0.16568    0.172741   
LR+: Positive likelihood ratio            169.767    47.2014     94.7968   
LR-: Negative likelihood ratio          0.0534018  0.0691942   0.0257593   
DOR: Diagnostic odds ratio                3179.05    682.159      3680.1  

In [10]:
stats['class'].loc['TP: True Positive'].mean()

1181.4

In [11]:
stats['class'].loc['FP: False Positive'].mean()

135.6

In [12]:
#Recall
stats['class'].loc['TPR: (Sensitivity, hit rate, recall)'].mean()

0.8522546559750295

In [13]:
stats['class'].loc['F1 score'].mean()

0.8723056377960295

In [14]:
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing

In [15]:
lb = preprocessing.LabelBinarizer()
lb.fit(y_test)
y_test_b = lb.transform(y_test)
y_test_pred_b = lb.transform(y_test_pred)
print(f"ROC Area: {roc_auc_score(y_test_b, y_test_pred_b, average=None).mean()}")

ROC Area: 0.9201353623583488
