In [39]:
import pandas as pd
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [10]:
x_train_data = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")

In [28]:
y = x_train_data.iloc[:,-1]
y = y.astype(int)
x = x_train_data.iloc[:, 0:1600]

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [34]:
nn = MLPClassifier(hidden_layer_sizes=(10,10,10))

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [37]:
predictions = nn.predict(X_test)

In [40]:
print(confusion_matrix(y_test,predictions))

[[367  35   0   2   2   1   0   0  20   1]
 [ 41 452   9   4   4   3   0   4  10   0]
 [  0   8 100   0   4   0   0   9   0   0]
 [  3   3   2 379  15   2   0   0   2   1]
 [  1   7   3   7 596   3   1   3   6   1]
 [  0   1   0   1   7 688   3   0  11   0]
 [  0   0   0   0   0   6 215   0   0   3]
 [  0  26  17   1   2   0   0  34   0   0]
 [ 10   6   0   0   2  11   1   0 559   0]
 [  0   0   0   2   0   0   2   0   0  79]]


In [41]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86       428
           1       0.84      0.86      0.85       527
           2       0.76      0.83      0.79       121
           3       0.96      0.93      0.94       407
           4       0.94      0.95      0.95       628
           5       0.96      0.97      0.97       711
           6       0.97      0.96      0.96       224
           7       0.68      0.42      0.52        80
           8       0.92      0.95      0.93       589
           9       0.93      0.95      0.94        83

   micro avg       0.91      0.91      0.91      3798
   macro avg       0.88      0.87      0.87      3798
weighted avg       0.91      0.91      0.91      3798



In [43]:
nn1 = MLPClassifier(hidden_layer_sizes=(20,20,20))
nn1.fit(X_train, y_train)
predictions1 = nn1.predict(X_test)
print(confusion_matrix(y_test,predictions1))
print(classification_report(y_test,predictions1))

[[406  10   0   1   0   5   1   0   5   0]
 [ 28 482   0   2   7   4   0   0   4   0]
 [  0   0 112   0   4   1   0   4   0   0]
 [  3   0   1 384   6   2   0   2   9   0]
 [  2   5   1   0 603   9   2   1   5   0]
 [  2   2   0   1   1 692   0   0  12   1]
 [  0   0   0   0   0   5 218   0   1   0]
 [  2   1   4   4   3   0   0  66   0   0]
 [  1   0   0   3   0   4   2   0 579   0]
 [  0   1   0   0   0   2   0   0   0  80]]
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       428
           1       0.96      0.91      0.94       527
           2       0.95      0.93      0.94       121
           3       0.97      0.94      0.96       407
           4       0.97      0.96      0.96       628
           5       0.96      0.97      0.96       711
           6       0.98      0.97      0.98       224
           7       0.90      0.82      0.86        80
           8       0.94      0.98      0.96       589
           9       0.99     

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [45]:
nn2 = MLPClassifier(hidden_layer_sizes=(30,30,30))
nn2.fit(X_train, y_train)
predictions2 = nn2.predict(X_test)
print(confusion_matrix(y_test,predictions2))
print(classification_report(y_test,predictions2))

[[389  31   0   2   0   2   0   0   4   0]
 [ 27 490   0   1   0   4   0   1   4   0]
 [  1   2 109   0   3   0   0   6   0   0]
 [  3   1   1 391   8   1   0   1   1   0]
 [  1   6   1   4 595   8   0   7   6   0]
 [  6   1   0   1   7 684   1   1  10   0]
 [  1   0   0   0   0   6 214   0   3   0]
 [  0   1   0   0   2   0   0  76   1   0]
 [  3   1   0   3   0   2   1   0 579   0]
 [  1   0   0   0   1   0   0   0   0  81]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       428
           1       0.92      0.93      0.92       527
           2       0.98      0.90      0.94       121
           3       0.97      0.96      0.97       407
           4       0.97      0.95      0.96       628
           5       0.97      0.96      0.96       711
           6       0.99      0.96      0.97       224
           7       0.83      0.95      0.88        80
           8       0.95      0.98      0.97       589
           9       1.00     

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
