In [8]:
import pandas as pd
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [2]:
x_train_data = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")

In [3]:
y = x_train_data.iloc[:,-1]
y = y.astype(int)
x = x_train_data.iloc[:, 0:1600]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [5]:
nn = MLPClassifier(hidden_layer_sizes=(10,))
nn.fit(X_train,y_train)
predictions = nn.predict(X_test)
print(f"Mean Accuracy Score: {nn.score(X_test,y_test)}")
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

Mean Accuracy Score: 0.9426013691416535
[[359  54   0   1   1   1   2   0   1   0]
 [ 23 531   0   0   8   5   3   0   0   0]
 [  1   0 124   0   1   0   0   4   0   0]
 [  1   5   0 367   6   1   0   2   1   0]
 [  2   7   0   8 613   2   2   1   3   0]
 [  1   3   0   3   3 629   2   1   2   0]
 [  0   0   0   0   0   1 234   0   3   0]
 [  7   2   7   0   3   0   0  45   1   0]
 [  7   1   0   0  16   2   3   2 586   0]
 [  0   0   0   0   0   0   2   0   0  92]]
              precision    recall  f1-score   support

           0       0.90      0.86      0.88       419
           1       0.88      0.93      0.91       570
           2       0.95      0.95      0.95       130
           3       0.97      0.96      0.96       383
           4       0.94      0.96      0.95       638
           5       0.98      0.98      0.98       644
           6       0.94      0.98      0.96       238
           7       0.82      0.69      0.75        65
           8       0.98      0.95      0.9

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## K-Fold

In [9]:
score = cross_val_score(nn,x,y,cv=10)

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, Converge

In [13]:
# Take the max and min of score
# Take the mean of the score
score
print(f"Min score ={score.min()}, Max score: {score.max()}, Mean Score = {score.mean()}")

Min score =0.8593996840442338, Max score: 0.9328593996840442, Mean Score = 0.9109794628751974
