In [9]:
import pandas as pd
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [2]:
x_train_data = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")

In [3]:
y = x_train_data.iloc[:,-1]
y = y.astype(int)
x = x_train_data.iloc[:, 0:1600]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [5]:
nn = MLPClassifier(hidden_layer_sizes=(10,))
nn.fit(X_train,y_train)
predictions = nn.predict(X_test)
print(f"Mean Accuracy Score: {nn.score(X_test,y_test)}")
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

Mean Accuracy Score: 0.8952080042127436
[[358  60   0   4   1   1   1   0   5   0]
 [ 92 462   0   8   7   2   4   1   4   0]
 [  0   7 104   0   2   0   0   2   0   0]
 [  2   1   1 362   3   0   0   0   4   0]
 [  2  13   2  10 582   4   0   2  16   0]
 [ 11   1   0   2   6 634   5   0   5   3]
 [  1   0   0   0   0   1 224   0   9   1]
 [  1   4  22   3  23   0   0  16   2   0]
 [  1   0   0   1   6   1   8   0 595   1]
 [  1   0   0   0   2  14   2   0   0  63]]
              precision    recall  f1-score   support

           0       0.76      0.83      0.80       430
           1       0.84      0.80      0.82       580
           2       0.81      0.90      0.85       115
           3       0.93      0.97      0.95       373
           4       0.92      0.92      0.92       631
           5       0.96      0.95      0.96       667
           6       0.92      0.95      0.93       236
           7       0.76      0.23      0.35        71
           8       0.93      0.97      0.9

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Grid search

In [24]:
gs = GridSearchCV(nn,param_grid={'hidden_layer_sizes':[(5,),(5,5),(5,5,5),(10,),(10,10),(10,10,10)],
                                "activation":['logistic', 'tanh', 'relu']})

In [25]:
gs.fit(x,y)

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  %

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, Converge

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'hidden_layer_sizes': [(5,), (5, 5), (5, 5, 5), (10,), (10, 10), (10, 10, 10)], 'activation': ['logistic', 'tanh', 'relu']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [26]:
gs.fit(x,y)

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  %

C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, Converge

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'hidden_layer_sizes': [(5,), (5, 5), (5, 5, 5), (10,), (10, 10), (10, 10, 10)], 'activation': ['logistic', 'tanh', 'relu']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [27]:
pd.DataFrame(gs.cv_results_)
print(gs.best_score_)
print(gs.best_params_)
print(gs.best_estimator_)

0.9244865718799368
{'activation': 'tanh', 'hidden_layer_sizes': (10,)}
MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)


C:\Users\singh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\singh\Anaconda3\lib\site-packages\sklearn\util

In [29]:
pd.DataFrame(gs.cv_results_)[['mean_test_score', 'std_test_score', 'params']]

mean_test_score  std_test_score  \
0          0.850632        0.006119   
1          0.830885        0.011795   
2          0.605608        0.012546   
3          0.896603        0.004911   
4          0.886098        0.013478   
5          0.842970        0.020606   
6          0.899526        0.005393   
7          0.898262        0.011172   
8          0.894076        0.010260   
9          0.924487        0.004827   
10         0.917852        0.010264   
11         0.918088        0.007424   
12         0.758452        0.048156   
13         0.709479        0.146464   
14         0.561453        0.284265   
15         0.861374        0.032613   
16         0.896130        0.014429   
17         0.872512        0.004623   

                                               params  
0   {'activation': 'logistic', 'hidden_layer_sizes...  
1   {'activation': 'logistic', 'hidden_layer_sizes...  
2   {'activation': 'logistic', 'hidden_layer_sizes...  
3   {'activation': 'logistic', 'hidden_layer_sizes...  
4   {'activation': 'logistic', 'hidden_layer_sizes...  
5   {'activation': 'logistic', 'hidden_layer_sizes...  
6   {'activation': 'tanh', 'hidden_layer_sizes': (...  
7   {'activation': 'tanh', 'hidden_layer_sizes': (...  
8   {'activation': 'tanh', 'hidden_layer_sizes': (...  
9   {'activation': 'tanh', 'hidden_layer_sizes': (...  
10  {'activation': 'tanh', 'hidden_layer_sizes': (...  
11  {'activation': 'tanh', 'hidden_layer_sizes': (...  
12  {'activation': 'relu', 'hidden_layer_sizes': (...  
13  {'activation': 'relu', 'hidden_layer_sizes': (...  
14  {'activation': 'relu', 'hidden_layer_sizes': (...  
15  {'activation': 'relu', 'hidden_layer_sizes': (...  
16  {'activation': 'relu', 'hidden_layer_sizes': (...  
17  {'activation': 'relu', 'hidden_layer_sizes': (...