In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import warnings
warnings.filterwarnings('ignore')

Reading in the data

In [2]:
x_train_data = pd.read_csv("x_train_normalised_with_y_train_smpl.csv", delimiter=",")
x_test_data = pd.read_csv("x_test_normalised_with_y_test_smpl.csv", delimiter=",")

In [5]:
x_train = x_train_data.iloc[:, 0:1600]
y_train = x_train_data.iloc[:,-1].astype(int)
x_test = x_test_data.iloc[:, 0:1600]
y_test = x_test_data.iloc[:,-1].astype(int)

## Changing the layers 

In [7]:
nn = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
nn.fit(x_train,y_train)
y_train_pred=cross_val_predict(nn,x_test,y_test,cv=10)
print("\nConfusion matrix from ten cross validation: \n", confusion_matrix(y_test, y_train_pred))
print("\n")
print("Classification report")
print(classification_report(y_test, y_train_pred))


Confusion matrix from ten cross validation: 
 [[321 107   0   1   8   5   0   0   8   0]
 [ 91 510   0   0  15   7   0   0   6   1]
 [  4  28  95   0  12   0   0   7   4   0]
 [  3   1   2 402  11   0   0   0   1   0]
 [  5  11   0   4 662   2   0   0   6   0]
 [ 10   4   0   1   4 692   0   0   7   2]
 [  3   0   0   1   0   1 256   0   9   0]
 [  0   3   5   3   8   0   0  39   2   0]
 [  0   0   0   0  13   0   6   0 671   0]
 [  9   0   1   3  11   7   0   0   5  54]]


Classification report
              precision    recall  f1-score   support

           0       0.72      0.71      0.72       450
           1       0.77      0.81      0.79       630
           2       0.92      0.63      0.75       150
           3       0.97      0.96      0.96       420
           4       0.89      0.96      0.92       690
           5       0.97      0.96      0.97       720
           6       0.98      0.95      0.96       270
           7       0.85      0.65      0.74        60
           

In [18]:
print("Results using test set:") 
print(nn.score(x_test,y_test))
y_test_pred=cross_val_predict(nn, x_test,y_test,cv=10)
print("\nConfusion matrix using test set:") 
print(confusion_matrix(y_test, y_test_pred))
print("Classification report:")
print(classification_report(y_test, y_test_pred))

Results using test set:
0.9261390887290167

Confusion matrix using test set:
[[291 138   0   1   7   4   1   0   7   1]
 [ 84 509   0   1  16   4   0   0  14   2]
 [ 13  16  83   0  24   0   5   2   7   0]
 [  2   1   0 393  20   0   1   0   3   0]
 [  4  13   4   7 649   2   1   0  10   0]
 [  3   2   0   1  10 690   0   0  11   3]
 [  0   0   0   6  14   1 238   0  11   0]
 [  1   0   8   2  19   0   0  27   3   0]
 [  3   0   0   2  18   3   3   0 660   1]
 [ 10   4   0   0  17   9   1   0  11  38]]
Classification report:
              precision    recall  f1-score   support

           0       0.71      0.65      0.68       450
           1       0.75      0.81      0.78       630
           2       0.87      0.55      0.68       150
           3       0.95      0.94      0.94       420
           4       0.82      0.94      0.87       690
           5       0.97      0.96      0.96       720
           6       0.95      0.88      0.92       270
           7       0.93      0.45   

In [29]:
def printReports(nn):
    nn.fit(x_train,y_train)
    y_train_pred=cross_val_predict(nn,x_test,y_test,cv=10)
    print("Results using train set")
    print(nn.score(x_train,y_train))
    print("\n")
    print("Confusion matrix from ten cross validation:") 
    print(confusion_matrix(y_test, y_train_pred))
    print("\n")
    print("Classification report")
    print(classification_report(y_test, y_train_pred))
    print("Using test set ------------------------------------------------------------")
    print("Results using test set:") 
    print(nn.score(x_test,y_test))
    y_test_pred=cross_val_predict(nn, x_test,y_test,cv=10)
    print("\nConfusion matrix using test set:") 
    print(confusion_matrix(y_test, y_test_pred))
    print("\nClassification report:")
    print(classification_report(y_test, y_test_pred))

In [23]:
nn2 = MLPClassifier(hidden_layer_sizes=(10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
nn2.fit(x_train,y_train)
y_train_pred2=cross_val_predict(nn2,x_test,y_test,cv=10)
print(nn2.score(x_train,y_train))
print("\n")
print("Confusion matrix from ten cross validation:") 
print(confusion_matrix(y_test, y_train_pred2))
print("\n")
print("Classification report")
print(classification_report(y_test, y_train_pred2))
print("Using test set ------------------------------------------------------------")
print("Results using test set:") 
print(nn2.score(x_test,y_test))
y_test_pred2=cross_val_predict(nn2, x_test,y_test,cv=10)
print("\nConfusion matrix using test set:") 
print(confusion_matrix(y_test, y_test_pred2))
print("Classification report:")
print(classification_report(y_test, y_test_pred2))

0.9611374407582939


Confusion matrix from ten cross validation:
[[359  74   0   1   5   0   3   0   7   1]
 [ 78 521   7   1  14   3   1   0   3   2]
 [  2  13 125   1   3   0   0   4   2   0]
 [  3   0   3 395  14   2   1   0   2   0]
 [  3   4   0   6 665   7   1   1   3   0]
 [  7   0   0   1   5 688   5   0  11   3]
 [  1   0   0   2   1   1 251   0  14   0]
 [  0   0   5   8   7   0   0  40   0   0]
 [  3   1   0   4   9   2   5   1 664   1]
 [  0   3   1   2  18   1   6   0   0  59]]


Classification report
              precision    recall  f1-score   support

           0       0.79      0.80      0.79       450
           1       0.85      0.83      0.84       630
           2       0.89      0.83      0.86       150
           3       0.94      0.94      0.94       420
           4       0.90      0.96      0.93       690
           5       0.98      0.96      0.97       720
           6       0.92      0.93      0.92       270
           7       0.87      0.67      0.75    

In [25]:
nn3 = MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

0.9503159557661928


Confusion matrix from ten cross validation:
[[353  63   1   1   6   6  10   0   9   1]
 [ 85 511   4   1  15   3   7   0   0   4]
 [  1  17 110   0  16   0   2   2   2   0]
 [  0   5   0 387  10   1   5   2   9   1]
 [  5  13   7   6 628   4   8   2  16   1]
 [ 23   6   0   1   9 657   1   0  17   6]
 [  4   2   0   1  11   1 232   0  19   0]
 [  0   0   6   4  12   0   0  35   3   0]
 [ 13   6   4   1  30   8  13   1 614   0]
 [  3  12   0   1  15   3   3   0   2  51]]


Classification report
              precision    recall  f1-score   support

           0       0.72      0.78      0.75       450
           1       0.80      0.81      0.81       630
           2       0.83      0.73      0.78       150
           3       0.96      0.92      0.94       420
           4       0.84      0.91      0.87       690
           5       0.96      0.91      0.94       720
           6       0.83      0.86      0.84       270
           7       0.83      0.58      0.69    

## Changing the neurons 

In [27]:
nn5 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn5)

Results using train set
0.9774091627172196


Confusion matrix from ten cross validation:
[[401  37   0   0   6   1   1   0   2   2]
 [ 40 572   0   3   7   5   0   0   3   0]
 [  4   1 133   0   0   0   0   8   4   0]
 [  0   4   1 408   6   0   0   0   1   0]
 [  3   6   0   1 672   2   0   1   5   0]
 [  1   0   0   1   6 708   0   0   3   1]
 [  0   0   0   0   0   0 266   0   3   1]
 [  0   0   2   0   0   0   0  58   0   0]
 [  0   1   0   0   5   1   1   0 682   0]
 [  1   2   0   0   0   1   0   0   1  85]]


Classification report
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       450
           1       0.92      0.91      0.91       630
           2       0.98      0.89      0.93       150
           3       0.99      0.97      0.98       420
           4       0.96      0.97      0.97       690
           5       0.99      0.98      0.98       720
           6       0.99      0.99      0.99       270
           7       0.87

In [30]:
nn3 = MLPClassifier(hidden_layer_sizes=(30,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn3)

Results using train set
0.9832543443917852


Confusion matrix from ten cross validation:
[[411  28   0   0   6   1   2   0   2   0]
 [ 31 584   0   2   6   5   0   0   2   0]
 [  4   0 138   0   0   0   0   6   2   0]
 [  0   3   1 410   5   0   0   0   1   0]
 [  2   4   0   3 677   2   0   0   2   0]
 [  2   0   0   1   4 709   0   0   3   1]
 [  0   0   0   0   0   0 267   0   3   0]
 [  0   0   1   0   0   0   0  59   0   0]
 [  0   0   0   0   4   0   0   0 686   0]
 [  0   2   0   0   0   1   0   0   1  86]]


Classification report
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       450
           1       0.94      0.93      0.93       630
           2       0.99      0.92      0.95       150
           3       0.99      0.98      0.98       420
           4       0.96      0.98      0.97       690
           5       0.99      0.98      0.99       720
           6       0.99      0.99      0.99       270
           7       0.91

In [31]:
nn4 = MLPClassifier(hidden_layer_sizes=(50,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=200)
printReports(nn4)

Results using train set
0.989652448657188


Confusion matrix from ten cross validation:
[[418  18   1   0   5   3   2   0   3   0]
 [ 22 591   0   2   8   4   0   0   1   2]
 [  2   0 143   0   2   0   0   2   1   0]
 [  0   4   0 409   6   0   0   0   1   0]
 [  2   5   0   1 678   3   0   0   1   0]
 [  1   0   0   1   3 711   0   0   3   1]
 [  0   0   0   0   0   0 269   0   1   0]
 [  0   0   1   0   0   0   0  59   0   0]
 [  0   0   0   0   6   1   0   1 682   0]
 [  1   1   0   0   0   1   0   0   1  86]]


Classification report
              precision    recall  f1-score   support

           0       0.94      0.93      0.93       450
           1       0.95      0.94      0.95       630
           2       0.99      0.95      0.97       150
           3       0.99      0.97      0.98       420
           4       0.96      0.98      0.97       690
           5       0.98      0.99      0.99       720
           6       0.99      1.00      0.99       270
           7       0.95 

## Changing iterations 

In [33]:
nn6 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=50)
printReports(nn6)

Results using train set
0.9313586097946287


Confusion matrix from ten cross validation:
[[271 149   0   1   6   5   6   0  12   0]
 [ 97 487   1   1  17   6   9   0  12   0]
 [  4  34  69   0  36   0   0   3   4   0]
 [  0   3   0 400  13   0   0   0   4   0]
 [  5  25   0  16 631   1   3   0   9   0]
 [  1  10   0   1  15 676   0   0  17   0]
 [  1   0   0   0   7   0 235   0  27   0]
 [  0   0  24   0  16   0   0  15   5   0]
 [  9   0   1   0  15   0   4   0 661   0]
 [  6   2   0   2  39   9   5   0  10  17]]


Classification report
              precision    recall  f1-score   support

           0       0.69      0.60      0.64       450
           1       0.69      0.77      0.73       630
           2       0.73      0.46      0.56       150
           3       0.95      0.95      0.95       420
           4       0.79      0.91      0.85       690
           5       0.97      0.94      0.95       720
           6       0.90      0.87      0.88       270
           7       0.83

In [34]:
nn7 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.001,max_iter=100)
printReports(nn7)

Results using train set
0.9576619273301737


Confusion matrix from ten cross validation:
[[332  99   1   1   7   3   3   0   4   0]
 [ 79 526   0   1  10   5   1   0   7   1]
 [  5  13 120   0   2   0   0   5   5   0]
 [  0   3   0 405  11   0   0   0   1   0]
 [  2  10   0   6 666   2   0   0   4   0]
 [  1   3   0   1   9 697   0   0   7   2]
 [  0   0   0   0   2   0 257   0  11   0]
 [  0   0  10   1   0   0   0  48   1   0]
 [  3   1   0   0   8   0   3   0 675   0]
 [  1   2   0   0   3   3   0   0   1  80]]


Classification report
              precision    recall  f1-score   support

           0       0.78      0.74      0.76       450
           1       0.80      0.83      0.82       630
           2       0.92      0.80      0.85       150
           3       0.98      0.96      0.97       420
           4       0.93      0.97      0.95       690
           5       0.98      0.97      0.97       720
           6       0.97      0.95      0.96       270
           7       0.91

## Change learning rate

In [35]:
nn8 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.01,max_iter=200)

printReports(nn8)

Results using train set
0.9880726698262243


Confusion matrix from ten cross validation:
[[423  16   0   1   3   3   2   0   2   0]
 [  6 613   0   1   5   3   0   0   2   0]
 [  3   0 143   1   1   0   0   1   1   0]
 [  2   3   0 405   6   0   0   1   1   2]
 [  2   3   0   5 673   3   1   0   3   0]
 [  1   2   0   2   2 711   0   0   2   0]
 [  1   0   0   1   1   0 266   0   1   0]
 [  0   0   0   0   0   0   0  60   0   0]
 [  0   2   1   1   6   3   0   1 676   0]
 [  0   1   0   0   1   1   0   0   1  86]]


Classification report
              precision    recall  f1-score   support

           0       0.97      0.94      0.95       450
           1       0.96      0.97      0.97       630
           2       0.99      0.95      0.97       150
           3       0.97      0.96      0.97       420
           4       0.96      0.98      0.97       690
           5       0.98      0.99      0.98       720
           6       0.99      0.99      0.99       270
           7       0.95

In [36]:
nn9 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.9,learning_rate_init=0.1,max_iter=200)
printReports(nn9)

Results using train set
0.5804897314375987


Confusion matrix from ten cross validation:
[[224 113   0   0  20  55   1   0  36   1]
 [ 65 404   4   0  60  73   1   0  21   2]
 [ 16  14  53   0  43  19   0   1   4   0]
 [  2   0   0 270  34  43   6   1  63   1]
 [ 15  33   1  13 528  84   0   1  14   1]
 [ 10  12   0   1  11 656   2   0  27   1]
 [  9   2   0   0  30  38 118   0  73   0]
 [  1   3   0  13  14   6   0  18   5   0]
 [ 18   7   0   2  33  85  11   2 532   0]
 [  8   8   0   0   2  17   1   0  24  30]]


Classification report
              precision    recall  f1-score   support

           0       0.61      0.50      0.55       450
           1       0.68      0.64      0.66       630
           2       0.91      0.35      0.51       150
           3       0.90      0.64      0.75       420
           4       0.68      0.77      0.72       690
           5       0.61      0.91      0.73       720
           6       0.84      0.44      0.58       270
           7       0.78

## Change momentum

In [37]:
nn10 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.7,learning_rate_init=0.001,max_iter=200)
printReports(nn10)

Results using train set
0.9737756714060032


Confusion matrix from ten cross validation:
[[388  50   0   0   5   1   2   0   3   1]
 [ 45 568   0   1   8   4   0   0   3   1]
 [  5   2 134   0   0   0   0   6   3   0]
 [  0   6   0 409   4   0   0   0   1   0]
 [  3   6   0   4 673   2   0   0   2   0]
 [  2   0   0   1   5 708   0   0   3   1]
 [  0   1   0   0   1   0 264   0   4   0]
 [  0   0   3   0   0   0   0  57   0   0]
 [  0   0   0   0   7   0   0   0 683   0]
 [  1   2   0   1   1   1   0   0   0  84]]


Classification report
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       450
           1       0.89      0.90      0.90       630
           2       0.98      0.89      0.93       150
           3       0.98      0.97      0.98       420
           4       0.96      0.98      0.97       690
           5       0.99      0.98      0.99       720
           6       0.99      0.98      0.99       270
           7       0.90

In [38]:
nn11 = MLPClassifier(hidden_layer_sizes=(20,), activation='relu', 
                   momentum=0.5,learning_rate_init=0.001,max_iter=200)

printReports(nn11)

Results using train set
0.9731437598736177


Confusion matrix from ten cross validation:
[[388  48   0   0   4   4   2   0   3   1]
 [ 52 561   0   2   6   6   0   0   3   0]
 [  3   2 134   0   1   0   0   7   3   0]
 [  0   5   0 408   6   0   0   0   1   0]
 [  1   8   0   4 671   3   0   0   3   0]
 [  1   0   0   1   4 709   0   0   3   2]
 [  0   0   0   1   0   0 266   0   2   1]
 [  0   0   3   0   0   0   0  56   1   0]
 [  1   1   0   0   6   1   1   0 679   1]
 [  0   2   0   0   1   1   0   0   1  85]]


Classification report
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       450
           1       0.89      0.89      0.89       630
           2       0.98      0.89      0.93       150
           3       0.98      0.97      0.98       420
           4       0.96      0.97      0.97       690
           5       0.98      0.98      0.98       720
           6       0.99      0.99      0.99       270
           7       0.89

## Change Validation Fraction

In [39]:
nn13 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.5)
printReports(nn13)

Results using train set
0.9525276461295419


Confusion matrix from ten cross validation:
[[335  95   1   1   5   6   3   0   4   0]
 [ 83 519   0   0  12   6   0   0  10   0]
 [ 10   7 120   0   4   0   0   5   4   0]
 [  0   6   0 402   9   1   0   0   2   0]
 [  3   9   0   7 661   3   0   0   6   1]
 [  3   3   0   1  10 694   1   0   6   2]
 [  0   0   0   0   0   0 259   0  10   1]
 [  0   0  13   0   2   0   0  42   3   0]
 [  3   1   0   1  10   0   5   1 669   0]
 [  0   2   0   0   5   3   0   0   1  79]]


Classification report
              precision    recall  f1-score   support

           0       0.77      0.74      0.76       450
           1       0.81      0.82      0.82       630
           2       0.90      0.80      0.85       150
           3       0.98      0.96      0.97       420
           4       0.92      0.96      0.94       690
           5       0.97      0.96      0.97       720
           6       0.97      0.96      0.96       270
           7       0.88

In [40]:
nn12 = MLPClassifier(hidden_layer_sizes=(20,),momentum=0.5,learning_rate_init=0.001,
                     max_iter=200, early_stopping=True,validation_fraction=0.7)
printReports(nn12)

Results using train set
0.9348341232227488


Confusion matrix from ten cross validation:
[[283 135   0   2   7   8   4   0  11   0]
 [105 477   2   1  16   9   4   0  15   1]
 [  8  27  67   0  38   1   0   5   4   0]
 [  1   5   2 395  17   0   0   0   0   0]
 [ 16  21   1  14 630   0   0   0   8   0]
 [  4   9   0   1  15 676   1   0  14   0]
 [  4   0   0   0   9   1 222   0  34   0]
 [  0   0  21   0  24   0   0  14   1   0]
 [ 10   1   4   0  13   0   3   1 658   0]
 [  4   2   0   4  33   9   0   0   3  35]]


Classification report
              precision    recall  f1-score   support

           0       0.65      0.63      0.64       450
           1       0.70      0.76      0.73       630
           2       0.69      0.45      0.54       150
           3       0.95      0.94      0.94       420
           4       0.79      0.91      0.84       690
           5       0.96      0.94      0.95       720
           6       0.95      0.82      0.88       270
           7       0.70